config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: '/emails' if Rails.env.development?

  devise_for :users
  root to: 'documents#index'
  resources :documents do
    collection do
      resources :available_hours, only: [:index], module: :documents
    end
  end

  resources :calendar, only: [:index] do
    collection do
      get :events
    end
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/document.rb
# frozen_string_literal: true

class Document < ApplicationRecord
  belongs_to :client, class_name: 'User', foreign_key: 'user_id', inverse_of: :documents

  validates :cmr_number, :taking_over_date, :taking_over_start_time, :taking_over_end_time, presence: true
  validates :cmr_number, uniqueness: true
  validate :not_overlapping

  def taking_over_start_at
    DateTime.parse("#{taking_over_date} #{taking_over_start_time}")
  end

  def taking_over_end_at
    DateTime.parse("#{taking_over_date} #{taking_over_end_time}")
  end

  private

  def not_overlapping
    documents = Document.where.not(id:)
                        .where(taking_over_date:)
                        .where('taking_over_start_time < ? AND taking_over_end_time > ?',
                               taking_over_end_time, taking_over_start_time)
    return if documents.blank?

    errors.add(:base, "Czas odbioru nakłada się na inny dokument: #{documents.map(&:cmr_number)}")
    errors.add(:taking_over_start_time, "Czas odbioru nakłada się na inny dokument: #{documents.map(&:cmr_number)}")
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :validatable

  ADMIN = 'admin'
  CLIENT = 'client'

  ROLES = [ADMIN, CLIENT].freeze

  enum role: { admin: ADMIN, client: CLIENT }

  has_many :documents, dependent: :destroy

  # Validations
  validates :role, presence: true, inclusion: { in: ROLES }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/authenticated_controller.rb
# frozen_string_literal: true

class AuthenticatedController < ApplicationController
  include Pundit::Authorization

  before_action :authenticate_user!
end

app/controllers/calendar_controller.rb
# frozen_string_literal: true

class CalendarController < AuthenticatedController
  def index; end

  def events
    render json: Document.all.map { |document|
                   { title: document.cmr_number,
                     start: document.taking_over_start_at,
                     end: document.taking_over_end_at,
                     url: document_path(document) }
                 }
  end
end

app/controllers/documents/available_hours_controller.rb
# frozen_string_literal: true

module Documents
  class AvailableHoursController < AuthenticatedController
    def index
      taking_over_date = Date.parse(params[:taking_over_date])

      collection = AvailableHours.new(taking_over_date).call

      render 'documents/available_hours/index', locals: { collection: }
    end
  end
end

app/controllers/documents_controller.rb
# frozen_string_literal: true

class DocumentsController < AuthenticatedController
  before_action :set_document, only: %i[show edit update destroy]

  def index
    render 'documents/index', locals: { documents: Document.order(created_at: :desc) }
  end

  def show
    render 'documents/show', locals: { document: @document }
  end

  def new
    document = Document.new
    render 'documents/new', locals: { document:, available_hours: [] }
  end

  def edit
    available_hours = ::AvailableHours.new(@document.taking_over_date, document: @document).call
    render 'documents/edit', locals: { document: @document, available_hours: }
  end

  def create
    if document_params[:taking_over_start_time].present?
      parsed_end_time = Time.zone.parse(document_params[:taking_over_start_time])
    end
    parsed_end_time = parsed_end_time.present? ? parsed_end_time + 30.minutes : nil

    document = Document.new(document_params.merge(
                              cmr_number: generate_cmr_number,
                              taking_over_end_time: parsed_end_time,
                              client: current_user
                            ))

    if document.save
      DocumentsMailer.create(document).deliver_later
      redirect_to document_url(document), notice: 'CMR utworzony.'
    else
      available_hours = ::AvailableHours.new(document.taking_over_date, document: @document).call

      render :new, status: :unprocessable_entity, locals: { document:, available_hours: }
    end
  end

  def update
    taking_over_end_time = Time.zone.parse(document_params[:taking_over_start_time]) + 30.minutes
    if @document.update(document_params.merge(taking_over_end_time:))
      redirect_to document_url(@document), notice: 'CMR zaktualizowany.'
    else
      available_hours = ::AvailableHours.new(@document.taking_over_date, document: @document).call
      render :edit, status: :unprocessable_entity, locals: { document: @document, available_hours: }
    end
  end

  def destroy
    @document.destroy!

    redirect_to documents_url, notice: 'CMR usunięty.'
  end

  private

  def set_document
    @document = Document.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to documents_url, alert: 'CMR nie istnieje.'
  end

  def generate_cmr_number
    number = Document.where(created_at: Time.zone.now.beginning_of_day..).count + 1
    I18n.l Date.current, format: :cmr, number: number.to_s.rjust(4, '0')
  end

  def document_params # rubocop:disable Metrics/MethodLength
    params.require(:document).permit(:sender, :consignee, :delivery_place, :taking_over_place,
                                     :documents, :marks_6_1, :number_7_1, :method_8_1,
                                     :nature_9_1, :number_10_1, :weight_11_1, :volume_12_1, :marks_6_2, :number_7_2,
                                     :method_8_2, :nature_9_2, :number_10_2, :weight_11_2, :volume_12_2, :marks_6_3,
                                     :number_7_3, :method_8_3, :nature_9_3, :number_10_3, :weight_11_3, :volume_12_3,
                                     :marks_6_4, :number_7_4, :method_8_4, :nature_9_4, :number_10_4, :weight_11_4,
                                     :volume_12_4, :class_6, :number_7, :letter_8, :adr_9, :sender_instructions_13,
                                     :carriage_instructions_14, :carriage_paid_14, :carriage_forward_14,
                                     :cash_on_delivery_15, :carrier_16, :carriers_plates_16, :successive_carriers_17,
                                     :carriers_reservations_18, :special_agreements_19, :established_in_21,
                                     :established_in_date_21, :taking_over_date, :taking_over_start_time, :products,
                                     :sender_signature)
  end
end

app/controllers/static_pages_controller.rb
# frozen_string_literal: true

class StaticPagesController < ApplicationController
  def home; end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < AuthenticatedController
  def index
    users = policy_scope(User)

    render 'users/index', locals: { users: }
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/documents/form_helper.rb
# frozen_string_literal: true

module Documents
  module FormHelper
    def argo
      <<~TEXT
        ARGO
        Katarzyna SZUMILAS Hanusiak
        18-106 Turośń Kościelna
        Ul. Wysokie 40
        NIP 8991496318
      TEXT
    end

    def bauer_blue_gmbh
      <<~TEXT
        BAUER BLUE GMBH
        Herstellung&Vartrieb
        Kolpingstrasse 24
        88416 Ochsenhausen Germany
      TEXT
    end

    def sender_collection
      [['ARGO', argo],
       ['BAUER BLUE GMBH', bauer_blue_gmbh]]
    end

    def taking_over_place_collection
      ['21-521 Zalesie', '21-512 Wólka Dobryńska']
    end

    def sender_signature_collection
      [['ARGO', argo + "\nMarcin Hanusiak"],
       ['BAUER BLUE GMBH', bauer_blue_gmbh + "\nMarcin Hanusiak"]]
    end
  end
end

app/views/calendar/index.html.erb
<h1 class="mb-4">Kalendarz</h1>
<div id="calendar" data-controller="calendar"></div>

app/views/documents/_cmr_document.html.erb
<div id="<%= dom_id document %>" class="border px-4 py-5 container">
  <div class="row">
    <div class="col border">
      1 Sender
      <%= document.sender %>
    </div>
    <div class="col border">
      CMR No. <%= document.cmr_number %>
    </div>
  </div>


  <div class="row">
    <div class="col border">
      2 Consignee
      <%= document.consignee %>
    </div>
    <div class="col border">
      16 Carrier
      <%= document.carrier %>
    </div>
  </div>

  <div class="row">
    <div class="col border">
      3 Place of delivery of the goods
      <%= document.place_of_delivery %>
    </div>
    <div class="col border">
      17 Successive carriers
      <%= document.successive_carrier %>
    </div>
  </div>

  <div class="row">
    <div class="col border">
      <div class="row">
        <div class="border border-start-0 border-end-0 border-top-0">
          4 Place and date of taking over the goods
          <%= document.place_and_date_of_taking_over_the_goods %>
        </div>
        <div class="border border-start-0 border-end-0 border-top-0 border-bottom-0">
          5 Documents attached
          <%= document.documents_attached %>
        </div>
      </div>

    </div>
    <div class="col border">
      18 Carrier's reservations and observations
      <%= document.carriers_reservations_and_observations %>
    </div>
  </div>


  <div class="row">
    <div class="col-8 border">
      <div class="row">
        <div class="col">6</div>
        <div class="col">7</div>
        <div class="col">8</div>
        <div class="col">9</div>
      </div>
    </div>
    <div class="border col-4">
      <div class="row">
        <div class="col-4">10</div>
        <div class="col-4">11</div>
        <div class="col-4">12</div>
      </div>
    </div>
  </div>


  <div class="row">
    <div class="col-8 border">
      <div class="row">
        <div class="col">Class</div>
        <div class="col">Number</div>
        <div class="col">Letter</div>
        <div class="col">9</div>
      </div>
    </div>
    <div class="border col-4">
      <div class="row">
        <div class="col-4">0</div>
        <div class="col-4">0</div>
        <div class="col-4">0</div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col border">
      <div class="row">
        <div class="border">13 Sender instructions</div>
        <div class="border h-auto">14 Instruction as to payment for carriage</div>
      </div>
    </div>
    <div class="col border">
      <div class="row">
        <div class="border">19 Special agreements</div>
        <div class="border">
          20 To be paid by
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col border">
      <div class="row">
        <div class="col">21 Established in 0</div>
        <div class="col">on 01-04-2024</div>
      </div>
    </div>
    <div class="col border">15 Cash on delivery 0</div>
  </div>

  <div class="row">
    <div class="col border">22</div>
    <div class="col border">23</div>
    <div class="col border">24</div>
  </div>
</div>

app/views/documents/_document.html.erb
<%= content_tag :h1, "CMR #{document.cmr_number}" %>

<div class="border p-2">
  <%= content_tag :h5, Document.human_attribute_name(:sender) %>
  <%= simple_format document.sender.presence || "Brak danych" %>
</div>

<div class="border p-2">
  <%= content_tag :h5, Document.human_attribute_name(:consignee) %>
  <%= document.consignee.presence || "Brak danych"  %>
</div>

<div class="border p-2">
  <%= content_tag :h5, Document.human_attribute_name(:delivery_place) %>
  <%= document.delivery_place.presence || "Brak danych"  %>
</div>

<div class="border p-2">
  <%= content_tag :h5, Document.human_attribute_name(:taking_over_place) %>
  <%= document.taking_over_place.presence || "Brak danych"  %>
</div>

<div class="border p-2">
  <%= content_tag :h5, Document.human_attribute_name(:taking_over_start_at) %>
  <%= l document.taking_over_start_at, format: :short %>
</div>

<div class="border p-2">
  <%= content_tag :h5, Document.human_attribute_name(:sender_signature) %>
  <%= simple_format document.sender_signature %>
</div>

app/views/documents/_form.html.erb
<%= simple_form_for(document) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :sender, collection: sender_collection %>
    <%= f.input :consignee, input_html: { rows: 5 } %>
    <%= f.input :delivery_place %>
    <%= f.input :taking_over_place, collection: taking_over_place_collection %>

    <div data-controller="available-hours">
      <%= f.input :taking_over_date, input_html: { data: { action: "change->available-hours#update" } } %>
      <%= f.input :taking_over_start_time, collection: available_hours,
                selected: f.object.taking_over_start_time.try(:strftime, '%H:%M').to_s,
                disabled: !document.persisted? && f.object.taking_over_date.blank?,
                wrapper_html: { id: "taking_over_start_time_wrapper" } %>
    </div>

    <%= f.input :documents %>

    <%#= f.input :marks_6_1 %>
    <%#= f.input :number_7_1 %>
    <%#= f.input :method_8_1 %>
    <%#= f.input :nature_9_1 %>
    <%= f.input :products, input_html: { rows: 5 } %>
    <%= f.input :number_10_1 %>
    <%= f.input :weight_11_1 %>
    <%= f.input :volume_12_1 %>
    <%#= f.input :marks_6_2 %>
    <%#= f.input :number_7_2 %>
    <%#= f.input :method_8_2 %>
    <%#= f.input :nature_9_2 %>
    <%#= f.input :number_10_2 %>
    <%#= f.input :weight_11_2 %>
    <%#= f.input :volume_12_2 %>

    <%#= f.input :marks_6_3 %>
    <%#= f.input :number_7_3 %>
    <%#= f.input :method_8_3 %>
    <%#= f.input :nature_9_3 %>
    <%#= f.input :number_10_3 %>
    <%#= f.input :weight_11_3 %>
    <%#= f.input :volume_12_3 %>
    <%#= f.input :marks_6_4 %>
    <%#= f.input :number_7_4 %>
    <%#= f.input :method_8_4 %>
    <%#= f.input :nature_9_4 %>
    <%#= f.input :number_10_4 %>
    <%#= f.input :weight_11_4 %>
    <%#= f.input :volume_12_4 %>

    <%#= f.input :class_6 %>
    <%#= f.input :number_7 %>
    <%#= f.input :letter_8 %>
    <%#= f.input :adr_9 %>

    <div class="d-none">
      <%= f.input :sender_instructions_13 %>
      <%= f.input :carriage_instructions_14 %>
      <%= f.input :carriage_paid_14 %>
      <%= f.input :carriage_forward_14 %>
      <%= f.input :cash_on_delivery_15 %>
    </div>

    <%= f.input :carrier_16 %>
    <%= f.input :carriers_plates_16 %>

    <div class="d-none">
      <%= f.input :successive_carriers_17 %>
      <%= f.input :carriers_reservations_18 %>
      <%= f.input :special_agreements_19 %>
    </div>

    <%= f.input :established_in_21 %>
    <%= f.input :established_in_date_21 %>
    <%= f.input :sender_signature, collection: sender_signature_collection %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, t(".submit") %>
  </div>
<% end %>

app/views/documents/available_hours/index.turbo_stream.erb
<%= simple_form_for(Document.new) do |f| %>
  <%= turbo_stream.replace "taking_over_start_time_wrapper" do %>
    <%= f.input :taking_over_start_time, collection:, wrapper_html: { id: "taking_over_start_time_wrapper" } %>
  <% end %>
<% end %>

app/views/documents/edit.html.erb
<h1>Edytuj</h1>

<%= render "form", document:, available_hours: %>

<br>

app/views/documents/index.html.erb
<h1>Dokumenty CMR</h1>

<div class="d-flex justify-content-between align-items-center mb-3">
  <p>Wszystkie dokumenty</p>
  <%= link_to "Nowy dokument", new_document_path, class: 'btn btn-primary' %>
</div>

<table class="table">
  <thead>
  <tr>
    <th scope="col">#</th>
    <th scope="col">CMR NR</th>
    <th scope="col">AKCJA</th>
  </tr>
  </thead>
  <tbody>
  <% documents.each do |document| %>
    <tr>
      <th scope="row"><%= document.id %></th>
      <td><%= document.cmr_number %></td>
      <td>
        <div class="d-flex gap-2">
          <%= link_to document, class: 'btn btn-outline-primary btn-sm' do %>
            Sczegóły <i class="fa-solid fa-eye"></i>
          <% end %>

          <%= render DownloadCmr.new(document:) %>
        </div>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/documents/new.html.erb
<h1>Nowy dokument CMR</h1>

<%= render "form", document:, available_hours: %>
<br>

app/views/documents/show.html.erb
<%= render document %>

<div class="mt-3">
  <%= link_to edit_document_path(document), class: 'btn btn-outline-primary' do %>
    Edytuj <i class="fa-solid fa-pen-to-square"></i>
  <% end %>

  <button type="button" class="btn btn-outline-danger" data-bs-toggle="modal" data-bs-target="#exampleModal">

    Usuń <i class="fa-solid fa-trash"></i>

  </button>
  <%= render Modal.new(document:) %>
  <%= render DownloadCmr.new(document: ) %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Argoksh</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
  <%= render NavbarComponent.new(current_user:) %>

  <div class="container">
    <% if notice %>
      <p class="alert alert-primary"><%= notice %></p>
    <% end %>

    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>
  </div>

  <script src="https://kit.fontawesome.com/f6bf98163c.js" crossorigin="anonymous"></script>
  </body>
</html>

app/views/users/index.html.erb
<h1>Klienci</h1>

<div class="d-flex justify-content-between align-items-center mb-3">
  <p>Wszyscy klienci</p>
  <%= link_to "Zaproś nowego klienta", new_user_invitation_path, class: 'btn btn-primary' %>
</div>

<table class="table">
  <thead>
  <tr>
    <th scope="col">#</th>
    <th scope="col">Email</th>
    <th scope="col">Rola</th>
    <th scope="col">Data przyjęcia zaproszenia</th>
  </tr>
  </thead>
  <tbody>
  <% users.each do |user| %>
    <tr>
      <th scope="row"><%= user.id %></th>
      <td><%= user.email %></td>
      <td><%= user.role %></td>
      <td><%= user.invitation_accepted_at.present? ? l(user.invitation_accepted_at, format: :short) : "" %></td>
    </tr>
  <% end %>
  </tbody>
</table>